name: search_select
description: "A Flutter widget for search and multi-select functionality with dropdown list."
version: 1.0.3
homepage: https://welitonsousa.vercel.app/
repository: https://github.com/welitonsousa/search_select
issue_tracker: https://github.com/welitonsousa/search_select/issues

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
